name = "pyscript example"
description = "A simple pyscript example"
packages = ["numpy", "pandas"]

[files]
"https://raw.githubusercontent.com/ed-kung/CSUN-Econ-310/main/_workspace/utils.py" = ""
"/CSUN-Econ-310/assets/data/math-review-practice.json" = ""
"/CSUN-Econ-310/assets/data/single-variable-optimization-practice.json" = ""
"/CSUN-Econ-310/assets/data/commodity-market-practice.json" = ""
"/CSUN-Econ-310/assets/data/labor-market-practice.json" = ""
"/CSUN-Econ-310/assets/data/general-equilibrium-practice.json" = ""
"/CSUN-Econ-310/assets/data/productivity-shocks-practice.json" = ""
"/CSUN-Econ-310/assets/data/multivariate-optimization-1-practice.json" = ""
"/CSUN-Econ-310/assets/data/multivariate-optimization-2-practice.json" = ""
"/CSUN-Econ-310/assets/data/lec10_practice.json" = ""
"/CSUN-Econ-310/assets/data/lec11_practice.json" = ""
"/CSUN-Econ-310/assets/data/lec12_practice.json" = ""
"/CSUN-Econ-310/assets/data/lec13_practice.json" = ""
"/CSUN-Econ-310/assets/data/lec14_practice.json" = ""
"/CSUN-Econ-310/assets/data/lec16_practice.json" = ""
"/CSUN-Econ-310/assets/data/lec17_practice.json" = ""
"/CSUN-Econ-310/assets/data/lec18_practice.json" = ""
"/CSUN-Econ-310/assets/data/lec19_practice.json" = ""
